#!/usr/bin/env python3
"""Open MPQ archives and emit a Markdown report of their contents.

For each archive: a file manifest, then a decoded section per file for every
type a decoder in decoders/ understands (CharBaseInfo.dbc combos, generic DBC
stats, text previews, …). Unknown binaries just appear in the manifest.

Usage:  python inspect.py <patch1.MPQ> [<patch2.MPQ> ...]  > report.md
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from decoders import render_all          # noqa: E402
from mpq_reader import open_archive       # noqa: E402


def inspect(path: str) -> str:
    out = []
    name = os.path.basename(path)
    size_kb = os.path.getsize(path) / 1024.0
    out.append(f"### `{name}`  ·  {size_kb:,.1f} KB\n")

    try:
        archive = open_archive(path)
    except Exception as e:  # noqa: BLE001
        out.append(f"> ⚠️ Could not open with the MPQ loader: `{e}`\n"
                   f"> May use a compression the loader doesn't support — "
                   f"try the StormLib backend.\n")
        return "\n".join(out)

    files = archive.files()
    if not files:
        out.append("> _(no listed files — archive has no `(listfile)`)_\n")
        return "\n".join(out)

    # cache contents once (also used by decoders)
    blobs = {}
    out.append("**Contained files**\n")
    out.append("| File | Size |")
    out.append("|------|-----:|")
    for f in files:
        try:
            blobs[f] = archive.read(f)
            fsize = f"{len(blobs[f]):,} B"
        except Exception:  # noqa: BLE001
            blobs[f] = None
            fsize = "?"
        out.append(f"| `{f}` | {fsize} |")
    out.append("")

    # per-file decoded sections
    for f in files:
        data = blobs.get(f)
        if data is None:
            continue
        section = render_all(f, data)
        if section:
            out.append(section)

    return "\n".join(out)


def main(argv) -> int:
    paths = [p for p in argv[1:] if p]
    if not paths:
        print("_No MPQ files to inspect._")
        return 0
    print("## 📦 MPQ patch inspection\n")
    print("_Auto-generated by "
          "[mpq-inspect-action](https://github.com/maluramichael/mpq-inspect-action)."
          "_\n")
    for p in paths:
        print(inspect(p))
        print("\n---\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
